remove hhvm from travis; phpunit processIsolation causes errors like the following?
PHPUnit_Framework_Exception: HipHop Notice: Nothing to do. Either pass a .php file to run, or use -m server